Documentos/proyecto/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :tests

  get 'bienvenida/index'

  root 'bienvenida#index'

  get 'publicacion' => 'publicacion#index'
  get 'publicacion/new' => 'publicacion#new'
  get 'publicacion/create' => 'publicacion#create'

end

Documentos/proyecto/app/models/publicacion.rb
class Publicacion < ActiveRecord::Base
end

Documentos/proyecto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Documentos/proyecto/app/controllers/publicacion_controller.rb
class PublicacionController < ApplicationController
	def index
		@publicaciones=Publicacion.all
	end

	def new
		@publicacion=Publicacion.new
	end

	def create
		@publicacion=Publicacion.new(params[:publicacion].permit(:titulo, :contenido))
		@publicacion.save
		redirect_to publicacion_path	#Se explica la ruta...
	end
end

Documentos/proyecto/app/helpers/application_helper.rb
module ApplicationHelper
end

Documentos/proyecto/app/helpers/publicacion_helper.rb
module PublicacionHelper
end

Documentos/proyecto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Documentos/proyecto/app/views/publicacion/_form.html.erb
<%= form_for :publicacion, url: publicacion_create_path do |f| %>
  <p>
    <%= f.label :titulo %></b>
    <%= f.text_field :titulo %>
  </p>
 
  <p>
    <%= f.label :contenido %></b>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

Documentos/proyecto/app/views/publicacion/form.html.erb
<%= form_for :publicacion, url: publicacion_create_path do |f| %>
  <p>
    <%= f.label :titulo %></b>
    <%= f.text_field :titulo %>
  </p>
 
  <p>
    <%= f.label :contenido %></b>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

Documentos/proyecto/app/views/publicacion/index.html.erb
<table>
	<thead>
		<tr>
			<th> Titulo </th>
			<th> Contenido </th>
		</tr>
	</thead>
	<tbody>
		<% @publicaciones.each do |publicacion| %>
			<tr>
				<td><%= publicacion.titulo %></td>
				<td><%= publicacion.contenido %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'Nueva publicacion', publicacion_new_path %>

Documentos/proyecto/app/views/publicacion/new.html.erb
<h1> Nueva publicacion </h1>
<%= render 'form' %>